//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle

  let entitlements = entitlements()
  let reuseIdentifier = reuseIdentifier()

  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 31 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `activeLineColor`.
    var activeLineColor: RswiftResources.ColorResource { .init(name: "activeLineColor", path: [], bundle: bundle) }

    /// Color `alertBackgroundColor`.
    var alertBackgroundColor: RswiftResources.ColorResource { .init(name: "alertBackgroundColor", path: [], bundle: bundle) }

    /// Color `approvedColor`.
    var approvedColor: RswiftResources.ColorResource { .init(name: "approvedColor", path: [], bundle: bundle) }

    /// Color `backgroundColor`.
    var backgroundColor: RswiftResources.ColorResource { .init(name: "backgroundColor", path: [], bundle: bundle) }

    /// Color `backgroundVaccinePhotos`.
    var backgroundVaccinePhotos: RswiftResources.ColorResource { .init(name: "backgroundVaccinePhotos", path: [], bundle: bundle) }

    /// Color `blurColor`.
    var blurColor: RswiftResources.ColorResource { .init(name: "blurColor", path: [], bundle: bundle) }

    /// Color `borderColor`.
    var borderColor: RswiftResources.ColorResource { .init(name: "borderColor", path: [], bundle: bundle) }

    /// Color `buttonColor`.
    var buttonColor: RswiftResources.ColorResource { .init(name: "buttonColor", path: [], bundle: bundle) }

    /// Color `calendarRangeColor`.
    var calendarRangeColor: RswiftResources.ColorResource { .init(name: "calendarRangeColor", path: [], bundle: bundle) }

    /// Color `calendarSelectDayColor`.
    var calendarSelectDayColor: RswiftResources.ColorResource { .init(name: "calendarSelectDayColor", path: [], bundle: bundle) }

    /// Color `canceledColor`.
    var canceledColor: RswiftResources.ColorResource { .init(name: "canceledColor", path: [], bundle: bundle) }

    /// Color `choosenBottomCardColor`.
    var choosenBottomCardColor: RswiftResources.ColorResource { .init(name: "choosenBottomCardColor", path: [], bundle: bundle) }

    /// Color `choosenCardTopColor`.
    var choosenCardTopColor: RswiftResources.ColorResource { .init(name: "choosenCardTopColor", path: [], bundle: bundle) }

    /// Color `dayColor`.
    var dayColor: RswiftResources.ColorResource { .init(name: "dayColor", path: [], bundle: bundle) }

    /// Color `deactiveLineColor`.
    var deactiveLineColor: RswiftResources.ColorResource { .init(name: "deactiveLineColor", path: [], bundle: bundle) }

    /// Color `declinedColor`.
    var declinedColor: RswiftResources.ColorResource { .init(name: "declinedColor", path: [], bundle: bundle) }

    /// Color `deleteTableCellColor`.
    var deleteTableCellColor: RswiftResources.ColorResource { .init(name: "deleteTableCellColor", path: [], bundle: bundle) }

    /// Color `editTableCellColor`.
    var editTableCellColor: RswiftResources.ColorResource { .init(name: "editTableCellColor", path: [], bundle: bundle) }

    /// Color `greenColor`.
    var greenColor: RswiftResources.ColorResource { .init(name: "greenColor", path: [], bundle: bundle) }

    /// Color `partiallyConfirmedColor`.
    var partiallyConfirmedColor: RswiftResources.ColorResource { .init(name: "partiallyConfirmedColor", path: [], bundle: bundle) }

    /// Color `partiallyConfirmedColor-1`.
    var partiallyConfirmedColor1: RswiftResources.ColorResource { .init(name: "partiallyConfirmedColor-1", path: [], bundle: bundle) }

    /// Color `pendingColor`.
    var pendingColor: RswiftResources.ColorResource { .init(name: "pendingColor", path: [], bundle: bundle) }

    /// Color `pickerChooseColor`.
    var pickerChooseColor: RswiftResources.ColorResource { .init(name: "pickerChooseColor", path: [], bundle: bundle) }

    /// Color `pickerColor`.
    var pickerColor: RswiftResources.ColorResource { .init(name: "pickerColor", path: [], bundle: bundle) }

    /// Color `rangeColor`.
    var rangeColor: RswiftResources.ColorResource { .init(name: "rangeColor", path: [], bundle: bundle) }

    /// Color `statusConfirmedColor`.
    var statusConfirmedColor: RswiftResources.ColorResource { .init(name: "statusConfirmedColor", path: [], bundle: bundle) }

    /// Color `statusOrderColor`.
    var statusOrderColor: RswiftResources.ColorResource { .init(name: "statusOrderColor", path: [], bundle: bundle) }

    /// Color `stepColor`.
    var stepColor: RswiftResources.ColorResource { .init(name: "stepColor", path: [], bundle: bundle) }

    /// Color `underTextViewLineColor`.
    var underTextViewLineColor: RswiftResources.ColorResource { .init(name: "underTextViewLineColor", path: [], bundle: bundle) }

    /// Color `vaccineColor`.
    var vaccineColor: RswiftResources.ColorResource { .init(name: "vaccineColor", path: [], bundle: bundle) }

    /// Color `waitingColor`.
    var waitingColor: RswiftResources.ColorResource { .init(name: "waitingColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 212 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `DeleteAction2`.
    var deleteAction2: RswiftResources.ImageResource { .init(name: "DeleteAction2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Ellipse`.
    var ellipse: RswiftResources.ImageResource { .init(name: "Ellipse", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Group 184`.
    var group184: RswiftResources.ImageResource { .init(name: "Group 184", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `HappyGoLucky_active`.
    var happyGoLucky_active: RswiftResources.ImageResource { .init(name: "HappyGoLucky_active", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `HappyGoLucky_unactive`.
    var happyGoLucky_unactive: RswiftResources.ImageResource { .init(name: "HappyGoLucky_unactive", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Mailbox`.
    var mailbox: RswiftResources.ImageResource { .init(name: "Mailbox", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `SaveButton`.
    var saveButton: RswiftResources.ImageResource { .init(name: "SaveButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Star`.
    var star: RswiftResources.ImageResource { .init(name: "Star", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Star_Filled`.
    var star_Filled: RswiftResources.ImageResource { .init(name: "Star_Filled", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `acceptOrderImage`.
    var acceptOrderImage: RswiftResources.ImageResource { .init(name: "acceptOrderImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `actionDone`.
    var actionDone: RswiftResources.ImageResource { .init(name: "actionDone", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `address`.
    var address: RswiftResources.ImageResource { .init(name: "address", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `alertBox`.
    var alertBox: RswiftResources.ImageResource { .init(name: "alertBox", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `alertBoxImageView`.
    var alertBoxImageView: RswiftResources.ImageResource { .init(name: "alertBoxImageView", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `alertCancelOrder`.
    var alertCancelOrder: RswiftResources.ImageResource { .init(name: "alertCancelOrder", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `alertFriendsBoxImageView`.
    var alertFriendsBoxImageView: RswiftResources.ImageResource { .init(name: "alertFriendsBoxImageView", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow`.
    var arrow: RswiftResources.ImageResource { .init(name: "arrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrowBackCalendarButton`.
    var arrowBackCalendarButton: RswiftResources.ImageResource { .init(name: "arrowBackCalendarButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrowBackImageView`.
    var arrowBackImageView: RswiftResources.ImageResource { .init(name: "arrowBackImageView", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow_righ`.
    var arrow_righ: RswiftResources.ImageResource { .init(name: "arrow_righ", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow_right`.
    var arrow_right: RswiftResources.ImageResource { .init(name: "arrow_right", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `attach`.
    var attach: RswiftResources.ImageResource { .init(name: "attach", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `backArrowCalendar`.
    var backArrowCalendar: RswiftResources.ImageResource { .init(name: "backArrowCalendar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `backButtonImage`.
    var backButtonImage: RswiftResources.ImageResource { .init(name: "backButtonImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `backToHomeImage`.
    var backToHomeImage: RswiftResources.ImageResource { .init(name: "backToHomeImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `back_tick`.
    var back_tick: RswiftResources.ImageResource { .init(name: "back_tick", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `belt`.
    var belt: RswiftResources.ImageResource { .init(name: "belt", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `big_chekbox_selected`.
    var big_chekbox_selected: RswiftResources.ImageResource { .init(name: "big_chekbox_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `billingAddressIcon`.
    var billingAddressIcon: RswiftResources.ImageResource { .init(name: "billingAddressIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bottomButtonArrow`.
    var bottomButtonArrow: RswiftResources.ImageResource { .init(name: "bottomButtonArrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bottomChek`.
    var bottomChek: RswiftResources.ImageResource { .init(name: "bottomChek", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `boy`.
    var boy: RswiftResources.ImageResource { .init(name: "boy", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `boySelected`.
    var boySelected: RswiftResources.ImageResource { .init(name: "boySelected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `boyUnselected`.
    var boyUnselected: RswiftResources.ImageResource { .init(name: "boyUnselected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `calendar`.
    var calendar: RswiftResources.ImageResource { .init(name: "calendar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `calendar-1`.
    var calendar1: RswiftResources.ImageResource { .init(name: "calendar-1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `calendarArrowButton`.
    var calendarArrowButton: RswiftResources.ImageResource { .init(name: "calendarArrowButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `calendarCheckbox`.
    var calendarCheckbox: RswiftResources.ImageResource { .init(name: "calendarCheckbox", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `calendarFullCheckbox`.
    var calendarFullCheckbox: RswiftResources.ImageResource { .init(name: "calendarFullCheckbox", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cancelOrderImage`.
    var cancelOrderImage: RswiftResources.ImageResource { .init(name: "cancelOrderImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `catSelected`.
    var catSelected: RswiftResources.ImageResource { .init(name: "catSelected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `catUnselected`.
    var catUnselected: RswiftResources.ImageResource { .init(name: "catUnselected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cat_act`.
    var cat_act: RswiftResources.ImageResource { .init(name: "cat_act", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cat_inact`.
    var cat_inact: RswiftResources.ImageResource { .init(name: "cat_inact", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `changePasswordImage`.
    var changePasswordImage: RswiftResources.ImageResource { .init(name: "changePasswordImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat`.
    var chat: RswiftResources.ImageResource { .init(name: "chat", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `checbox_selected`.
    var checbox_selected: RswiftResources.ImageResource { .init(name: "checbox_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `checkImage`.
    var checkImage: RswiftResources.ImageResource { .init(name: "checkImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `checkboxBlack`.
    var checkboxBlack: RswiftResources.ImageResource { .init(name: "checkboxBlack", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `checkbox_selected_point`.
    var checkbox_selected_point: RswiftResources.ImageResource { .init(name: "checkbox_selected_point", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `checkbox_selected_point_black`.
    var checkbox_selected_point_black: RswiftResources.ImageResource { .init(name: "checkbox_selected_point_black", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `checkbox_unselected`.
    var checkbox_unselected: RswiftResources.ImageResource { .init(name: "checkbox_unselected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `city`.
    var city: RswiftResources.ImageResource { .init(name: "city", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cityIcon`.
    var cityIcon: RswiftResources.ImageResource { .init(name: "cityIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `clock`.
    var clock: RswiftResources.ImageResource { .init(name: "clock", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `close`.
    var close: RswiftResources.ImageResource { .init(name: "close", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `closeEmailIcon`.
    var closeEmailIcon: RswiftResources.ImageResource { .init(name: "closeEmailIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `closeTest`.
    var closeTest: RswiftResources.ImageResource { .init(name: "closeTest", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `close_eye`.
    var close_eye: RswiftResources.ImageResource { .init(name: "close_eye", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `close_thin`.
    var close_thin: RswiftResources.ImageResource { .init(name: "close_thin", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `comment`.
    var comment: RswiftResources.ImageResource { .init(name: "comment", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `commentIcon`.
    var commentIcon: RswiftResources.ImageResource { .init(name: "commentIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `commentsSignUpIcon`.
    var commentsSignUpIcon: RswiftResources.ImageResource { .init(name: "commentsSignUpIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `createSelectedButton`.
    var createSelectedButton: RswiftResources.ImageResource { .init(name: "createSelectedButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `createUnselectedButton`.
    var createUnselectedButton: RswiftResources.ImageResource { .init(name: "createUnselectedButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `crossAddContact`.
    var crossAddContact: RswiftResources.ImageResource { .init(name: "crossAddContact", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `crossForTextFieldError`.
    var crossForTextFieldError: RswiftResources.ImageResource { .init(name: "crossForTextFieldError", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `customView`.
    var customView: RswiftResources.ImageResource { .init(name: "customView", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dailyCheckInImage`.
    var dailyCheckInImage: RswiftResources.ImageResource { .init(name: "dailyCheckInImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `daycareImage`.
    var daycareImage: RswiftResources.ImageResource { .init(name: "daycareImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `deleteAction`.
    var deleteAction: RswiftResources.ImageResource { .init(name: "deleteAction", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `direction 1`.
    var direction1: RswiftResources.ImageResource { .init(name: "direction 1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dogAvatar`.
    var dogAvatar: RswiftResources.ImageResource { .init(name: "dogAvatar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dogSelected`.
    var dogSelected: RswiftResources.ImageResource { .init(name: "dogSelected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dogUnselected`.
    var dogUnselected: RswiftResources.ImageResource { .init(name: "dogUnselected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dogWalkingImage`.
    var dogWalkingImage: RswiftResources.ImageResource { .init(name: "dogWalkingImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dogWalksRed`.
    var dogWalksRed: RswiftResources.ImageResource { .init(name: "dogWalksRed", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dog_act`.
    var dog_act: RswiftResources.ImageResource { .init(name: "dog_act", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dog_inact`.
    var dog_inact: RswiftResources.ImageResource { .init(name: "dog_inact", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `doghouse`.
    var doghouse: RswiftResources.ImageResource { .init(name: "doghouse", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `doghouse_solid`.
    var doghouse_solid: RswiftResources.ImageResource { .init(name: "doghouse_solid", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `dollar`.
    var dollar: RswiftResources.ImageResource { .init(name: "dollar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `doneButtonImage`.
    var doneButtonImage: RswiftResources.ImageResource { .init(name: "doneButtonImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `doorCode`.
    var doorCode: RswiftResources.ImageResource { .init(name: "doorCode", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `edit`.
    var edit: RswiftResources.ImageResource { .init(name: "edit", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `editAction`.
    var editAction: RswiftResources.ImageResource { .init(name: "editAction", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `editButton`.
    var editButton: RswiftResources.ImageResource { .init(name: "editButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `editPhoto`.
    var editPhoto: RswiftResources.ImageResource { .init(name: "editPhoto", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `email`.
    var email: RswiftResources.ImageResource { .init(name: "email", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `email_link`.
    var email_link: RswiftResources.ImageResource { .init(name: "email_link", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `email_link_registration`.
    var email_link_registration: RswiftResources.ImageResource { .init(name: "email_link_registration", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `emalIcon`.
    var emalIcon: RswiftResources.ImageResource { .init(name: "emalIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `emergencyContactIcon`.
    var emergencyContactIcon: RswiftResources.ImageResource { .init(name: "emergencyContactIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `employee_test`.
    var employee_test: RswiftResources.ImageResource { .init(name: "employee_test", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `eye`.
    var eye: RswiftResources.ImageResource { .init(name: "eye", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `feed`.
    var feed: RswiftResources.ImageResource { .init(name: "feed", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `feedRed`.
    var feedRed: RswiftResources.ImageResource { .init(name: "feedRed", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `finickyFido_active`.
    var finickyFido_active: RswiftResources.ImageResource { .init(name: "finickyFido_active", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `finickyFido_unactive`.
    var finickyFido_unactive: RswiftResources.ImageResource { .init(name: "finickyFido_unactive", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `flower`.
    var flower: RswiftResources.ImageResource { .init(name: "flower", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `forgotPasswordImage`.
    var forgotPasswordImage: RswiftResources.ImageResource { .init(name: "forgotPasswordImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `girl`.
    var girl: RswiftResources.ImageResource { .init(name: "girl", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `girlSelected`.
    var girlSelected: RswiftResources.ImageResource { .init(name: "girlSelected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `girlUnselected`.
    var girlUnselected: RswiftResources.ImageResource { .init(name: "girlUnselected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `greyFirstStepReport`.
    var greyFirstStepReport: RswiftResources.ImageResource { .init(name: "greyFirstStepReport", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `greySecondStepReport`.
    var greySecondStepReport: RswiftResources.ImageResource { .init(name: "greySecondStepReport", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `greyThirdStepReport`.
    var greyThirdStepReport: RswiftResources.ImageResource { .init(name: "greyThirdStepReport", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `heart`.
    var heart: RswiftResources.ImageResource { .init(name: "heart", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `heart_bordered`.
    var heart_bordered: RswiftResources.ImageResource { .init(name: "heart_bordered", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `hearts`.
    var hearts: RswiftResources.ImageResource { .init(name: "hearts", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `hideMoreImage`.
    var hideMoreImage: RswiftResources.ImageResource { .init(name: "hideMoreImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `home`.
    var home: RswiftResources.ImageResource { .init(name: "home", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `homeAddressBackground`.
    var homeAddressBackground: RswiftResources.ImageResource { .init(name: "homeAddressBackground", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `homeAddressButton`.
    var homeAddressButton: RswiftResources.ImageResource { .init(name: "homeAddressButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `homeAddressCheck`.
    var homeAddressCheck: RswiftResources.ImageResource { .init(name: "homeAddressCheck", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `homeAddressIcon`.
    var homeAddressIcon: RswiftResources.ImageResource { .init(name: "homeAddressIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `homeAlarmSystemIcon`.
    var homeAlarmSystemIcon: RswiftResources.ImageResource { .init(name: "homeAlarmSystemIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `key`.
    var key: RswiftResources.ImageResource { .init(name: "key", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `keyExtras`.
    var keyExtras: RswiftResources.ImageResource { .init(name: "keyExtras", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `keyTest`.
    var keyTest: RswiftResources.ImageResource { .init(name: "keyTest", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `leftArrow`.
    var leftArrow: RswiftResources.ImageResource { .init(name: "leftArrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `left_arrow_big`.
    var left_arrow_big: RswiftResources.ImageResource { .init(name: "left_arrow_big", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `location`.
    var location: RswiftResources.ImageResource { .init(name: "location", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `locationIcon`.
    var locationIcon: RswiftResources.ImageResource { .init(name: "locationIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `locationImage`.
    var locationImage: RswiftResources.ImageResource { .init(name: "locationImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `lockBoxIcon`.
    var lockBoxIcon: RswiftResources.ImageResource { .init(name: "lockBoxIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `lockboxLocationIcon`.
    var lockboxLocationIcon: RswiftResources.ImageResource { .init(name: "lockboxLocationIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `logOutCustomerAccount`.
    var logOutCustomerAccount: RswiftResources.ImageResource { .init(name: "logOutCustomerAccount", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `logo`.
    var logo: RswiftResources.ImageResource { .init(name: "logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `lovehouse`.
    var lovehouse: RswiftResources.ImageResource { .init(name: "lovehouse", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `lovehouse_solid`.
    var lovehouse_solid: RswiftResources.ImageResource { .init(name: "lovehouse_solid", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `mailboxIcon`.
    var mailboxIcon: RswiftResources.ImageResource { .init(name: "mailboxIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `map`.
    var map: RswiftResources.ImageResource { .init(name: "map", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `mastercard_icon`.
    var mastercard_icon: RswiftResources.ImageResource { .init(name: "mastercard_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `meetGreetIcon`.
    var meetGreetIcon: RswiftResources.ImageResource { .init(name: "meetGreetIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `meet_n_greet`.
    var meet_n_greet: RswiftResources.ImageResource { .init(name: "meet_n_greet", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `menu`.
    var menu: RswiftResources.ImageResource { .init(name: "menu", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `moreArrowImageView`.
    var moreArrowImageView: RswiftResources.ImageResource { .init(name: "moreArrowImageView", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `nextButtonImage`.
    var nextButtonImage: RswiftResources.ImageResource { .init(name: "nextButtonImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `noButtonImage`.
    var noButtonImage: RswiftResources.ImageResource { .init(name: "noButtonImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `noWarning`.
    var noWarning: RswiftResources.ImageResource { .init(name: "noWarning", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `notes`.
    var notes: RswiftResources.ImageResource { .init(name: "notes", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ok`.
    var ok: RswiftResources.ImageResource { .init(name: "ok", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `okBtnImage`.
    var okBtnImage: RswiftResources.ImageResource { .init(name: "okBtnImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `okButtomImage`.
    var okButtomImage: RswiftResources.ImageResource { .init(name: "okButtomImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `orderArrowImage`.
    var orderArrowImage: RswiftResources.ImageResource { .init(name: "orderArrowImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `other`.
    var other: RswiftResources.ImageResource { .init(name: "other", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `otherHomeAccessIcon`.
    var otherHomeAccessIcon: RswiftResources.ImageResource { .init(name: "otherHomeAccessIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `otherRequestsIcon`.
    var otherRequestsIcon: RswiftResources.ImageResource { .init(name: "otherRequestsIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `overnight`.
    var overnight: RswiftResources.ImageResource { .init(name: "overnight", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `overnightIcon`.
    var overnightIcon: RswiftResources.ImageResource { .init(name: "overnightIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pause`.
    var pause: RswiftResources.ImageResource { .init(name: "pause", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pee`.
    var pee: RswiftResources.ImageResource { .init(name: "pee", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `peeRed`.
    var peeRed: RswiftResources.ImageResource { .init(name: "peeRed", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pet`.
    var pet: RswiftResources.ImageResource { .init(name: "pet", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pet_photo_placeholder`.
    var pet_photo_placeholder: RswiftResources.ImageResource { .init(name: "pet_photo_placeholder", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `pets`.
    var pets: RswiftResources.ImageResource { .init(name: "pets", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `phone`.
    var phone: RswiftResources.ImageResource { .init(name: "phone", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `phoneIcon`.
    var phoneIcon: RswiftResources.ImageResource { .init(name: "phoneIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `photo_placeholder`.
    var photo_placeholder: RswiftResources.ImageResource { .init(name: "photo_placeholder", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `placeForButtonImage`.
    var placeForButtonImage: RswiftResources.ImageResource { .init(name: "placeForButtonImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `plantExtras`.
    var plantExtras: RswiftResources.ImageResource { .init(name: "plantExtras", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `play`.
    var play: RswiftResources.ImageResource { .init(name: "play", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `plus`.
    var plus: RswiftResources.ImageResource { .init(name: "plus", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `poop`.
    var poop: RswiftResources.ImageResource { .init(name: "poop", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `poopRed`.
    var poopRed: RswiftResources.ImageResource { .init(name: "poopRed", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `profile_test`.
    var profile_test: RswiftResources.ImageResource { .init(name: "profile_test", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `reportFirstStepImage`.
    var reportFirstStepImage: RswiftResources.ImageResource { .init(name: "reportFirstStepImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `reportSecondStepImage`.
    var reportSecondStepImage: RswiftResources.ImageResource { .init(name: "reportSecondStepImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `reportThirdStepImage`.
    var reportThirdStepImage: RswiftResources.ImageResource { .init(name: "reportThirdStepImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `reset_pass`.
    var reset_pass: RswiftResources.ImageResource { .init(name: "reset_pass", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `saveButton-1`.
    var saveButton1: RswiftResources.ImageResource { .init(name: "saveButton-1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `selectPetsAlertImage`.
    var selectPetsAlertImage: RswiftResources.ImageResource { .init(name: "selectPetsAlertImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sendButtonImageView`.
    var sendButtonImageView: RswiftResources.ImageResource { .init(name: "sendButtonImageView", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sendWarningButton`.
    var sendWarningButton: RswiftResources.ImageResource { .init(name: "sendWarningButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `service_boarding`.
    var service_boarding: RswiftResources.ImageResource { .init(name: "service_boarding", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `service_meet_and_greet`.
    var service_meet_and_greet: RswiftResources.ImageResource { .init(name: "service_meet_and_greet", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `service_pet_sitting`.
    var service_pet_sitting: RswiftResources.ImageResource { .init(name: "service_pet_sitting", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `service_pet_taxi`.
    var service_pet_taxi: RswiftResources.ImageResource { .init(name: "service_pet_taxi", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `shareFriendImage`.
    var shareFriendImage: RswiftResources.ImageResource { .init(name: "shareFriendImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sitter`.
    var sitter: RswiftResources.ImageResource { .init(name: "sitter", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `sittingCatImage`.
    var sittingCatImage: RswiftResources.ImageResource { .init(name: "sittingCatImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smallAnimalSelected`.
    var smallAnimalSelected: RswiftResources.ImageResource { .init(name: "smallAnimalSelected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smallAnimalUnselected`.
    var smallAnimalUnselected: RswiftResources.ImageResource { .init(name: "smallAnimalUnselected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `small_act`.
    var small_act: RswiftResources.ImageResource { .init(name: "small_act", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `small_arrow_right`.
    var small_arrow_right: RswiftResources.ImageResource { .init(name: "small_arrow_right", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `small_inact`.
    var small_inact: RswiftResources.ImageResource { .init(name: "small_inact", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `snallAnimalSelected`.
    var snallAnimalSelected: RswiftResources.ImageResource { .init(name: "snallAnimalSelected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `state`.
    var state: RswiftResources.ImageResource { .init(name: "state", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `stateIcon`.
    var stateIcon: RswiftResources.ImageResource { .init(name: "stateIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `summaryOfVisiticon`.
    var summaryOfVisiticon: RswiftResources.ImageResource { .init(name: "summaryOfVisiticon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `taxi`.
    var taxi: RswiftResources.ImageResource { .init(name: "taxi", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `test`.
    var test: RswiftResources.ImageResource { .init(name: "test", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tick_right`.
    var tick_right: RswiftResources.ImageResource { .init(name: "tick_right", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `toBookImageButton`.
    var toBookImageButton: RswiftResources.ImageResource { .init(name: "toBookImageButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `toOrdersButtonImage`.
    var toOrdersButtonImage: RswiftResources.ImageResource { .init(name: "toOrdersButtonImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `topButtonArrow`.
    var topButtonArrow: RswiftResources.ImageResource { .init(name: "topButtonArrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `totalOrderArrowImage`.
    var totalOrderArrowImage: RswiftResources.ImageResource { .init(name: "totalOrderArrowImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `trashImageView`.
    var trashImageView: RswiftResources.ImageResource { .init(name: "trashImageView", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `underTextViewLine`.
    var underTextViewLine: RswiftResources.ImageResource { .init(name: "underTextViewLine", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `union`.
    var union: RswiftResources.ImageResource { .init(name: "union", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `user`.
    var user: RswiftResources.ImageResource { .init(name: "user", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `vaccinePhotoButton`.
    var vaccinePhotoButton: RswiftResources.ImageResource { .init(name: "vaccinePhotoButton", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `validationCheckBox`.
    var validationCheckBox: RswiftResources.ImageResource { .init(name: "validationCheckBox", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `viewCustomerProfileImage`.
    var viewCustomerProfileImage: RswiftResources.ImageResource { .init(name: "viewCustomerProfileImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `water`.
    var water: RswiftResources.ImageResource { .init(name: "water", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `waterRed`.
    var waterRed: RswiftResources.ImageResource { .init(name: "waterRed", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `white_checbox`.
    var white_checbox: RswiftResources.ImageResource { .init(name: "white_checbox", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `yesButtonImage`.
    var yesButtonImage: RswiftResources.ImageResource { .init(name: "yesButtonImage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `yesWarning`.
    var yesWarning: RswiftResources.ImageResource { .init(name: "yesWarning", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `zip`.
    var zip: RswiftResources.ImageResource { .init(name: "zip", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `zipIcon`.
    var zipIcon: RswiftResources.ImageResource { .init(name: "zipIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.entitlements` struct is generated, and contains static references to 0 properties.
  struct entitlements {
    let apsEnvironment: String = "development"
  }

  /// This `_R.font` struct is generated, and contains static references to 16 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `Aileron-Black`.
    var aileronBlack: RswiftResources.FontResource { .init(name: "Aileron-Black", bundle: bundle, filename: "Aileronblack.ttf") }

    /// Font `Aileron-BlackItalic`.
    var aileronBlackItalic: RswiftResources.FontResource { .init(name: "Aileron-BlackItalic", bundle: bundle, filename: "Aileronblackitalic.ttf") }

    /// Font `Aileron-Bold`.
    var aileronBold: RswiftResources.FontResource { .init(name: "Aileron-Bold", bundle: bundle, filename: "Aileronbold.ttf") }

    /// Font `Aileron-BoldItalic`.
    var aileronBoldItalic: RswiftResources.FontResource { .init(name: "Aileron-BoldItalic", bundle: bundle, filename: "Aileronbolditalic.ttf") }

    /// Font `Aileron-Heavy`.
    var aileronHeavy: RswiftResources.FontResource { .init(name: "Aileron-Heavy", bundle: bundle, filename: "Aileronheavy.ttf") }

    /// Font `Aileron-HeavyItalic`.
    var aileronHeavyItalic: RswiftResources.FontResource { .init(name: "Aileron-HeavyItalic", bundle: bundle, filename: "Aileronheavyitalic.ttf") }

    /// Font `Aileron-Italic`.
    var aileronItalic: RswiftResources.FontResource { .init(name: "Aileron-Italic", bundle: bundle, filename: "Aileronitalic.ttf") }

    /// Font `Aileron-Light`.
    var aileronLight: RswiftResources.FontResource { .init(name: "Aileron-Light", bundle: bundle, filename: "Aileronlight.ttf") }

    /// Font `Aileron-LightItalic`.
    var aileronLightItalic: RswiftResources.FontResource { .init(name: "Aileron-LightItalic", bundle: bundle, filename: "Aileronlightitalic.ttf") }

    /// Font `Aileron-Regular`.
    var aileronRegular: RswiftResources.FontResource { .init(name: "Aileron-Regular", bundle: bundle, filename: "Aileron.ttf") }

    /// Font `Aileron-SemiBold`.
    var aileronSemiBold: RswiftResources.FontResource { .init(name: "Aileron-SemiBold", bundle: bundle, filename: "Aileronsemibold.ttf") }

    /// Font `Aileron-SemiBoldItalic`.
    var aileronSemiBoldItalic: RswiftResources.FontResource { .init(name: "Aileron-SemiBoldItalic", bundle: bundle, filename: "Aileronsemibolditalic.ttf") }

    /// Font `Aileron-Thin`.
    var aileronThin: RswiftResources.FontResource { .init(name: "Aileron-Thin", bundle: bundle, filename: "Aileronthin.ttf") }

    /// Font `Aileron-ThinItalic`.
    var aileronThinItalic: RswiftResources.FontResource { .init(name: "Aileron-ThinItalic", bundle: bundle, filename: "Aileronthinitalic.ttf") }

    /// Font `Aileron-UltraLight`.
    var aileronUltraLight: RswiftResources.FontResource { .init(name: "Aileron-UltraLight", bundle: bundle, filename: "Aileronultralight.ttf") }

    /// Font `Aileron-UltraLightItalic`.
    var aileronUltraLightItalic: RswiftResources.FontResource { .init(name: "Aileron-UltraLightItalic", bundle: bundle, filename: "Aileronultralightitalic.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [aileronBlack, aileronBlackItalic, aileronBold, aileronBoldItalic, aileronHeavy, aileronHeavyItalic, aileronItalic, aileronLight, aileronLightItalic, aileronRegular, aileronSemiBold, aileronSemiBoldItalic, aileronThin, aileronThinItalic, aileronUltraLight, aileronUltraLightItalic].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 18 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Aileron.ttf`.
    var aileronTtf: RswiftResources.FileResource { .init(name: "Aileron", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronblack.ttf`.
    var aileronblackTtf: RswiftResources.FileResource { .init(name: "Aileronblack", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronblackitalic.ttf`.
    var aileronblackitalicTtf: RswiftResources.FileResource { .init(name: "Aileronblackitalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronbold.ttf`.
    var aileronboldTtf: RswiftResources.FileResource { .init(name: "Aileronbold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronbolditalic.ttf`.
    var aileronbolditalicTtf: RswiftResources.FileResource { .init(name: "Aileronbolditalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronheavy.ttf`.
    var aileronheavyTtf: RswiftResources.FileResource { .init(name: "Aileronheavy", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronheavyitalic.ttf`.
    var aileronheavyitalicTtf: RswiftResources.FileResource { .init(name: "Aileronheavyitalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronitalic.ttf`.
    var aileronitalicTtf: RswiftResources.FileResource { .init(name: "Aileronitalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronlight.ttf`.
    var aileronlightTtf: RswiftResources.FileResource { .init(name: "Aileronlight", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronlightitalic.ttf`.
    var aileronlightitalicTtf: RswiftResources.FileResource { .init(name: "Aileronlightitalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronsemibold.ttf`.
    var aileronsemiboldTtf: RswiftResources.FileResource { .init(name: "Aileronsemibold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronsemibolditalic.ttf`.
    var aileronsemibolditalicTtf: RswiftResources.FileResource { .init(name: "Aileronsemibolditalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronthin.ttf`.
    var aileronthinTtf: RswiftResources.FileResource { .init(name: "Aileronthin", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronthinitalic.ttf`.
    var aileronthinitalicTtf: RswiftResources.FileResource { .init(name: "Aileronthinitalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronultralight.ttf`.
    var aileronultralightTtf: RswiftResources.FileResource { .init(name: "Aileronultralight", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Aileronultralightitalic.ttf`.
    var aileronultralightitalicTtf: RswiftResources.FileResource { .init(name: "Aileronultralightitalic", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `p103-customer.entitlements.xml`.
    var p103CustomerEntitlementsXml: RswiftResources.FileResource { .init(name: "p103-customer.entitlements", pathExtension: "xml", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 47 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `ActionAttachmentsCell`.
    var actionAttachmentsCell: RswiftResources.NibReferenceReuseIdentifier<ActionAttachmentsCell, ActionAttachmentsCell> { .init(name: "ActionAttachmentsCell", bundle: bundle, identifier: "ActionAttachmentsCell") }

    /// Nib `AddressView`.
    var addressView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "AddressView", bundle: bundle) }

    /// Nib `BaseButton`.
    var baseButton: RswiftResources.NibReference<UIKit.UIView> { .init(name: "BaseButton", bundle: bundle) }

    /// Nib `ButtonWithTrailingCheckbox`.
    var buttonWithTrailingCheckbox: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ButtonWithTrailingCheckbox", bundle: bundle) }

    /// Nib `CardCell`.
    var cardCell: RswiftResources.NibReference<CardCell> { .init(name: "CardCell", bundle: bundle) }

    /// Nib `CardCollectionViewCell`.
    var cardCollectionViewCell: RswiftResources.NibReference<CardCollectionViewCell> { .init(name: "CardCollectionViewCell", bundle: bundle) }

    /// Nib `CreateOrderTotalView`.
    var createOrderTotalView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CreateOrderTotalView", bundle: bundle) }

    /// Nib `CustomAlertView`.
    var customAlertView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CustomAlertView", bundle: bundle) }

    /// Nib `CustomMarker`.
    var customMarker: RswiftResources.NibReference<CustomMarker> { .init(name: "CustomMarker", bundle: bundle) }

    /// Nib `CustomerBottomSheetController`.
    var customerBottomSheetController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CustomerBottomSheetController", bundle: bundle) }

    /// Nib `CustomerEmployeeArrivesCell`.
    var customerEmployeeArrivesCell: RswiftResources.NibReferenceReuseIdentifier<CustomerEmployeeArrivesCell, CustomerEmployeeArrivesCell> { .init(name: "CustomerEmployeeArrivesCell", bundle: bundle, identifier: "CustomerEmployeeArrivesCell") }

    /// Nib `CustomerMapViewController`.
    var customerMapViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "CustomerMapViewController", bundle: bundle) }

    /// Nib `CustomerPetActionCell`.
    var customerPetActionCell: RswiftResources.NibReferenceReuseIdentifier<CustomerPetActionCell, CustomerPetActionCell> { .init(name: "CustomerPetActionCell", bundle: bundle, identifier: "CustomerPetActionCell") }

    /// Nib `CustomerPetActionTableViewCell`.
    var customerPetActionTableViewCell: RswiftResources.NibReference<CustomerPetActionTableViewCell> { .init(name: "CustomerPetActionTableViewCell", bundle: bundle) }

    /// Nib `CustomerSummaryTableCell`.
    var customerSummaryTableCell: RswiftResources.NibReferenceReuseIdentifier<CustomerSummaryTableCell, CustomerSummaryTableCell> { .init(name: "CustomerSummaryTableCell", bundle: bundle, identifier: "CustomerSummaryTableCell") }

    /// Nib `DayCountCell`.
    var dayCountCell: RswiftResources.NibReference<DayCountCell> { .init(name: "DayCountCell", bundle: bundle) }

    /// Nib `DescriptionCell`.
    var descriptionCell: RswiftResources.NibReference<DescriptionCell> { .init(name: "DescriptionCell", bundle: bundle) }

    /// Nib `EmployeeArrivesCell`.
    var employeeArrivesCell: RswiftResources.NibReference<EmployeeArrivesCell> { .init(name: "EmployeeArrivesCell", bundle: bundle) }

    /// Nib `ErrorAlert`.
    var errorAlert: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ErrorAlert", bundle: bundle) }

    /// Nib `MapBottomSheetViewController`.
    var mapBottomSheetViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MapBottomSheetViewController", bundle: bundle) }

    /// Nib `MapTopViewCll`.
    var mapTopViewCll: RswiftResources.NibReference<MapTopViewCll> { .init(name: "MapTopViewCll", bundle: bundle) }

    /// Nib `MapViewController`.
    var mapViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "MapViewController", bundle: bundle) }

    /// Nib `OrderDetailsDateHeader`.
    var orderDetailsDateHeader: RswiftResources.NibReference<UIKit.UIView> { .init(name: "OrderDetailsDateHeader", bundle: bundle) }

    /// Nib `PaymentAlertView`.
    var paymentAlertView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PaymentAlertView", bundle: bundle) }

    /// Nib `PetActionImagesColwCell`.
    var petActionImagesColwCell: RswiftResources.NibReferenceReuseIdentifier<PetActionImagesColwCell, PetActionImagesColwCell> { .init(name: "PetActionImagesColwCell", bundle: bundle, identifier: "PetActionImagesColwCell") }

    /// Nib `PetActionListCell`.
    var petActionListCell: RswiftResources.NibReferenceReuseIdentifier<PetActionListCell, PetActionListCell> { .init(name: "PetActionListCell", bundle: bundle, identifier: "PetActionListCell") }

    /// Nib `PetActionTableViewCell`.
    var petActionTableViewCell: RswiftResources.NibReferenceReuseIdentifier<PetActionTableViewCell, PetActionTableViewCell> { .init(name: "PetActionTableViewCell", bundle: bundle, identifier: "PetActionTableViewCell") }

    /// Nib `PetCell`.
    var petCell: RswiftResources.NibReference<PetCell> { .init(name: "PetCell", bundle: bundle) }

    /// Nib `PetImageCell`.
    var petImageCell: RswiftResources.NibReferenceReuseIdentifier<PetImageCell, PetImageCell> { .init(name: "PetImageCell", bundle: bundle, identifier: "PetImageCell") }

    /// Nib `PetWithNameCell`.
    var petWithNameCell: RswiftResources.NibReference<PetWithNameCell> { .init(name: "PetWithNameCell", bundle: bundle) }

    /// Nib `PetsTopView`.
    var petsTopView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PetsTopView", bundle: bundle) }

    /// Nib `ProfileNavigationView`.
    var profileNavigationView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ProfileNavigationView", bundle: bundle) }

    /// Nib `ReportCustomerCardViewController`.
    var reportCustomerCardViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ReportCustomerCardViewController", bundle: bundle) }

    /// Nib `SameForAllDayView`.
    var sameForAllDayView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SameForAllDayView", bundle: bundle) }

    /// Nib `SecondaryButton`.
    var secondaryButton: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SecondaryButton", bundle: bundle) }

    /// Nib `SitterRatingCardVC`.
    var sitterRatingCardVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SitterRatingCardVC", bundle: bundle) }

    /// Nib `SitterReviewCell`.
    var sitterReviewCell: RswiftResources.NibReference<SitterReviewCell> { .init(name: "SitterReviewCell", bundle: bundle) }

    /// Nib `SkyFloatingLabelTextFieldWithIconAndAccessory`.
    var skyFloatingLabelTextFieldWithIconAndAccessory: RswiftResources.NibReference<UIKit.UIView> { .init(name: "SkyFloatingLabelTextFieldWithIconAndAccessory", bundle: bundle) }

    /// Nib `SummarryTableViewCell`.
    var summarryTableViewCell: RswiftResources.NibReference<SummarryTableViewCell> { .init(name: "SummarryTableViewCell", bundle: bundle) }

    /// Nib `SummaryCell`.
    var summaryCell: RswiftResources.NibReference<SummaryCell> { .init(name: "SummaryCell", bundle: bundle) }

    /// Nib `SummaryDataCell`.
    var summaryDataCell: RswiftResources.NibReferenceReuseIdentifier<SummaryDataCell, SummaryDataCell> { .init(name: "SummaryDataCell", bundle: bundle, identifier: "SummaryDataCell") }

    /// Nib `TimeOffCell`.
    var timeOffCell: RswiftResources.NibReference<TimeOffCell> { .init(name: "TimeOffCell", bundle: bundle) }

    /// Nib `TimePickerView`.
    var timePickerView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "TimePickerView", bundle: bundle) }

    /// Nib `TopViewCell`.
    var topViewCell: RswiftResources.NibReference<TopViewCell> { .init(name: "TopViewCell", bundle: bundle) }

    /// Nib `TransactionCell`.
    var transactionCell: RswiftResources.NibReference<TransactionCell> { .init(name: "TransactionCell", bundle: bundle) }

    /// Nib `VisitHistoryActionCell`.
    var visitHistoryActionCell: RswiftResources.NibReference<VisitHistoryActionCell> { .init(name: "VisitHistoryActionCell", bundle: bundle) }

    /// Nib `YesOrNoView`.
    var yesOrNoView: RswiftResources.NibReference<UIKit.UIView> { .init(name: "YesOrNoView", bundle: bundle) }

    func validate() throws {
      if UIKit.UIImage(named: "address", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'address' is used in nib 'AddressView', but couldn't be loaded.") }
      if UIKit.UIImage(named: "checkbox_unselected", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'checkbox_unselected' is used in nib 'ButtonWithTrailingCheckbox', but couldn't be loaded.") }
      if UIKit.UIImage(named: "mastercard_icon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'mastercard_icon' is used in nib 'CardCollectionViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "white_checbox", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'white_checbox' is used in nib 'CardCollectionViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "customView", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'customView' is used in nib 'CustomMarker', but couldn't be loaded.") }
      if UIKit.UIImage(named: "meet_n_greet", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'meet_n_greet' is used in nib 'CustomerEmployeeArrivesCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "activeLineColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'activeLineColor' is used in nib 'CustomerEmployeeArrivesCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "dogWalksRed", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'dogWalksRed' is used in nib 'CustomerPetActionCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "summaryOfVisiticon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'summaryOfVisiticon' is used in nib 'CustomerSummaryTableCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "stepColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'stepColor' is used in nib 'CustomerSummaryTableCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "meet_n_greet", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'meet_n_greet' is used in nib 'EmployeeArrivesCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "activeLineColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'activeLineColor' is used in nib 'EmployeeArrivesCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "dogWalksRed", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'dogWalksRed' is used in nib 'MapTopViewCll', but couldn't be loaded.") }
      if UIKit.UIColor(named: "pendingColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'pendingColor' is used in nib 'MapTopViewCll', but couldn't be loaded.") }
      if UIKit.UIImage(named: "close_thin", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'close_thin' is used in nib 'PaymentAlertView', but couldn't be loaded.") }
      if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "plus") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'plus' is used in nib 'PetActionListCell', but couldn't be loaded.") } }
      if UIKit.UIColor(named: "activeLineColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'activeLineColor' is used in nib 'PetActionListCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "dogWalksRed", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'dogWalksRed' is used in nib 'PetActionTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "boy", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'boy' is used in nib 'PetCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "profile_test", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'profile_test' is used in nib 'PetWithNameCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "bottomButtonArrow", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'bottomButtonArrow' is used in nib 'PetsTopView', but couldn't be loaded.") }
      if UIKit.UIImage(named: "plus", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'plus' is used in nib 'SecondaryButton', but couldn't be loaded.") }
      if UIKit.UIImage(named: "summaryOfVisiticon", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'summaryOfVisiticon' is used in nib 'SummarryTableViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "stepColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'stepColor' is used in nib 'SummarryTableViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "bottomButtonArrow", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'bottomButtonArrow' is used in nib 'TimeOffCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "dogWalksRed", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'dogWalksRed' is used in nib 'TopViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "approvedColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'approvedColor' is used in nib 'TopViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "partiallyConfirmedColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'partiallyConfirmedColor' is used in nib 'TopViewCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "pendingColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'pendingColor' is used in nib 'TopViewCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "meet_n_greet", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'meet_n_greet' is used in nib 'VisitHistoryActionCell', but couldn't be loaded.") }
      if UIKit.UIColor(named: "activeLineColor", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Color named 'activeLineColor' is used in nib 'VisitHistoryActionCell', but couldn't be loaded.") }
      if UIKit.UIImage(named: "checkbox_unselected", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'checkbox_unselected' is used in nib 'YesOrNoView', but couldn't be loaded.") }
    }
  }

  /// This `_R.reuseIdentifier` struct is generated, and contains static references to 9 reuse identifiers.
  struct reuseIdentifier {

    /// Reuse identifier `ActionAttachmentsCell`.
    let actionAttachmentsCell: RswiftResources.ReuseIdentifier<ActionAttachmentsCell> = .init(identifier: "ActionAttachmentsCell")

    /// Reuse identifier `CustomerEmployeeArrivesCell`.
    let customerEmployeeArrivesCell: RswiftResources.ReuseIdentifier<CustomerEmployeeArrivesCell> = .init(identifier: "CustomerEmployeeArrivesCell")

    /// Reuse identifier `CustomerPetActionCell`.
    let customerPetActionCell: RswiftResources.ReuseIdentifier<CustomerPetActionCell> = .init(identifier: "CustomerPetActionCell")

    /// Reuse identifier `CustomerSummaryTableCell`.
    let customerSummaryTableCell: RswiftResources.ReuseIdentifier<CustomerSummaryTableCell> = .init(identifier: "CustomerSummaryTableCell")

    /// Reuse identifier `PetActionImagesColwCell`.
    let petActionImagesColwCell: RswiftResources.ReuseIdentifier<PetActionImagesColwCell> = .init(identifier: "PetActionImagesColwCell")

    /// Reuse identifier `PetActionListCell`.
    let petActionListCell: RswiftResources.ReuseIdentifier<PetActionListCell> = .init(identifier: "PetActionListCell")

    /// Reuse identifier `PetActionTableViewCell`.
    let petActionTableViewCell: RswiftResources.ReuseIdentifier<PetActionTableViewCell> = .init(identifier: "PetActionTableViewCell")

    /// Reuse identifier `PetImageCell`.
    let petImageCell: RswiftResources.ReuseIdentifier<PetImageCell> = .init(identifier: "PetImageCell")

    /// Reuse identifier `SummaryDataCell`.
    let summaryDataCell: RswiftResources.ReuseIdentifier<SummaryDataCell> = .init(identifier: "SummaryDataCell")
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {
        if UIKit.UIImage(named: "logo", in: bundle, compatibleWith: nil) == nil { throw RswiftResources.ValidationError("[R.swift] Image named 'logo' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
      }
    }
  }
}